[project]
name = "conversor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tata-14Dev", email = "tomy.uriel.s@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "markitdown[all]>=0.1.7",
    "pytesseract>=0.3.13",
    "pypdfium2>=4.30.0",
]

[project.scripts]
conversor = "conversor:main"

[project.gui-scripts]
conversor-gui = "conversor.gui:gui_main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]
